# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b990249996cd566e9dcc5ca42d3f48bb792ef8546f58a71b08e66a974dd686757799b2b42206d6c67da547809025ec4bddcc06b1795c63bb4645fb43c3d70f0

test:
  secret_key_base: ef5539ad41f43fccc2e4a6f5007a89960436a308149a2b6317d1773aed4d5760a1cc1ea64db224f9bf07cb57d570ac1d73538f489bf6df33739867172ac31a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
